name: terraform-docs
run-name: generate terraform-docs ${{ github.event.pull_request.title }}
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all
    
jobs:
  generate-terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"
          git-commit-message: "terraform-docs: update README.md"
          args: "--hide requirements"
